local arcl = {}; lvl = {}; tempbase = {}

local function articleInput(articleString, levelOfArticle)
  table.insert(arcl, articleString)
  table.insert(lvl, levelOfArticle)
end

articleInput('Избиение', 2) -- изначально указывается статья, которая будет записана в диалоге по порядку, который вы сейчас укажите, а вторым значением указывается уровень розыска.
articleInput('Вооруженное нападение на гражданских', 3) -- добавление новых статей производится ТОЛЬКО функцией articleInput(articleString, levelOfArticle)
articleInput('Вооруженное нападение на гос.сотрудников', 6)
articleInput('Убийство с отягщающими обстоятельствами', 2)
articleInput('Наезд на пешехода', 2)
articleInput('Игнорирование специальных сирен', 1)
articleInput('Хулиганство', 1)
articleInput('Угрозы', 1)
articleInput('Провокации', 2)
articleInput('Попрошайничество', 1)
articleInput('Оскорбление', 2)
articleInput('Угон транспортного средства', 2)
articleInput('Неподчинение правоохранительным органам', 1)
articleInput('Попытка скрыться', 2)
articleInput('Побег из тюрьмы', 6)
articleInput('Ношение оружия без лицензии', 1)
articleInput('Изнасилование', 3)
articleInput('Изготовление оружия нелегальным способом', 3)
articleInput('Изготовление наркотиков', 3)
articleInput('Хранение материалов', 3)
articleInput('Хранение наркотиков', 3)
articleInput('Употребление наркотиков', 3)
articleInput('Повреждение чужого имущества', 1)
articleInput('Уничтожение чужого имущества', 4)
articleInput('Проникновение на охраняемую территорию', 2)
articleInput('Проникновение на частную территорию', 1)
articleInput('Ограбление', 3)
articleInput('Вымогательство', 2)
articleInput('Мошенничество', 2)
articleInput('Взлом базы данных полиции', 1)
articleInput('Предложение интимных услуг', 1)
articleInput('Укрывательство', 2)
articleInput('Использование фальшивых документов', 1)
articleInput('Клевета', 1)
articleInput('Клевета на организацию', 2)
articleInput('Продажа военного имущества', 3)
articleInput('Покупка военной формы', 2)
articleInput('Покупка ключей от камеры', 6)
articleInput('Продажа ключей от камеры', 6)
articleInput('Кража ключей от камеры', 6)
articleInput('Предложение взятки', 2)
articleInput('Организация нелегальных мероприятий', 2)
articleInput('Совершение теракта', 6)
articleInput('Похищение', 6)
articleInput('Управление т/с в наркотическом или алкогольном опьянении', 1)

table.insert(tempbase, arcl)
table.insert(tempbase, lvl)
table.insert(tempbase, radio)
table.insert(tempbase, megaphone)
table.insert(tempbase, doing)
return tempbase
